### ISSUE TITLE
InternalServerError

### ISSUE THREAD

**Issue by gregruthenbeck** [vasanthdeveloper/ghata#16] opened 2020-10-05 15:16 UTC
I followed your install guide and it seemed ok until I tried to upload an image to an article. Then `ghost log` showed the following errors.

```
[2020-10-05 17:02:55] INFO Ghost is running in production...
[2020-10-05 17:02:55] INFO Your site is now available on https://ghost.something.com/
[2020-10-05 17:02:55] INFO Ctrl+C to shut down
[2020-10-05 17:02:55] INFO Ghost boot 2.974s
[2020-10-05 17:02:55] INFO Bootstrap client was closed.
[2020-10-05 17:03:00] INFO "PUT /ghost/api/v3/admin/posts//" 200 233ms
[2020-10-05 17:03:08] INFO "PUT /ghost/api/v3/admin/posts//" 200 95ms
[2020-10-05 17:03:14] ERROR "POST /ghost/api/v3/admin/images/upload/" 400 209ms

NAME: InternalServerError
CODE: InvalidArgument
MESSAGE: The server has encountered an error.

level: normal

InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost.something.com/versions/3.35.3/node_modules/@tryghost/errors/lib/errors.js:10:26)
    at _private.prepareError (/var/www/ghost.something.com/versions/3.35.3/core/server/web/shared/middlewares/error-handler.js:53:19)
    at Layer.handle_error (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost.something.com/versions/3.35.3/node_modules/express/lib/router/route.js:127:14)
    at /var/www/ghost.something.com/versions/3.35.3/core/server/api/shared/http.js:102:17

InvalidArgument: null
    at Request.extractError (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/ghost.something.com/versions/3.35.3/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by vasanthdeveloper** [comment] 2020-10-05 16:03
Is that a docker installation or a typical installation?
If it's a docker installation, please post the environment variables set in `docker-compose.yml`, if it's a typical installation please post the `config.production.json`.

> Note: Remove any sensitive information like API keys, etc.

**Comment by gregruthenbeck** [comment] 2020-10-05 18:20
Not a docker install.

Relevant part of my config.production.json contains:

```
 "storage": {
    "active": "ghata",
    "ghata": {
      "endpoint": "fra1.digitaloceanspaces.com",
      "subdomain": "cdn.mydom.com",
      "spacePath": "ghost_site",
      "bucket": "https://mydo.fra1.digitaloceanspaces.com",
      "key": "This_has_my_DO_API_key",
      "secret": "This_has_my_DO_API_Secret"
```

**Comment by vasanthdeveloper** [comment] 2020-10-05 18:26
![Screenshot 2020-10-05 at 11 53 56 PM](https://user-images.githubusercontent.com/24322511/95117376-21334980-0766-11eb-872f-0c9112fa39da.png)
Hmm, 🧐 could you post a screenshot of your DigitalOcean space name? Like this. ☝️
I am guessing `bucket` is wrongly configured.

**Comment by vasanthdeveloper** [comment] 2020-10-05 18:29
@gregruthenbeck Thank you! 🥳
You have created my first-ever, GitHub Issue! 😍

**Comment by gregruthenbeck** [comment] 2020-10-05 18:36
![image](https://user-images.githubusercontent.com/3433739/95118298-bc222880-0752-11eb-9d89-8993cdb8d701.png)

**Comment by vasanthdeveloper** [comment] 2020-10-05 18:40
Please do the following replacements 👇 and see if the issue is resolved.
```diff
- "bucket": "https://mydo.fra1.digitaloceanspaces.com",
+ "bucket": "exagen",
```

**Comment by gregruthenbeck** [comment] 2020-10-05 18:49
Brilliant! Thanks 👍 
Seems to be working. Have yet to test... but thanks for open-sourcing this

**Comment by vasanthdeveloper** [comment] 2020-10-05 18:50
Please test it, 🙂 so I can close the issue. Thanks for raising an issue here. This is my first GitHub issue 😇

**Comment by gregruthenbeck** [comment] 2020-10-05 19:01
Works ok... buuuut.... Isn't serving optimized (scaled) images. It seems to break that(?)

**Comment by vasanthdeveloper** [comment] 2020-10-05 19:06
🍯 **ghata** currently doesn't support image optimization. But this is certainly planned for the future.

**Closed by vasanthdeveloper** 2020-10-05 19:06 UTC
Labels: bug
